### ISSUE TITLE
feat(pages/index): create gutter for content

### ISSUE THREAD

**Issue by mianuddin** [slohacks/club#23]
* create a wrapping `section` that uses CSS grid to create a gutter along the sides of the page
* see `slohacks/recruiting` for reference

**Comment by mianuddin** [comment]
@stonewallstan in the interests of time I can handle this myself, unless you want to complete it at the meeting today

**Comment by stonewallstan** [comment]
@mianuddin I was planning on doing it either before the meeting today or directly after the meeting today. But working on it at the meeting works for me as well.

**Comment by mianuddin** [comment]
@stonewallstan feel free to start it now, the actual content of the meeting won't take too long, so I expect that we'll have this issue done by the end of it

**Comment by stonewallstan** [comment]
@mianuddin Sounds good! I have been looking over the recruiting grid for a little help implementing it.
