### ISSUE TITLE
feat(pages/index): our partners section

### ISSUE THREAD

**Issue by mianuddin** [slohacks/club#6]
* this section is prepended by a header of size `h2` which says "Our Partners"
* replicate the following schematic
* generic placeholders may be used as logos for now
> We're honored to be partnered with some awesome organizations and companies.
> {logo} {logo}

**Comment by stonewallstan** [comment]
I accidentally labeled "feat(pages/index): add our partners section"  incorrectly. It referenced issue number 8 instead of issue number 6. The changes on "feat(pages/index): add our partners section" dealt with this issue number and not issue number 8.
